### ISSUE TITLE
Página: inicio

### ISSUE THREAD

**Issue by joaquinodz** [joaquinodz/grupo_1_roper#3]
Home del sitio con la oferta de productos y / o servicios.

Historias de usuario:
- Como​ cliente ​quiero​ ver un resumen de la oferta de productos ​para​ poder decidirrápidamente si quedarme o buscar el producto en otro sitio. 
- Como​ cliente ​quiero​ que el sitio funcione bien en mi teléfono celular ​para​ poderacceder en cualquier momento.

**Entregable**:​ Archivo index.html junto con todos los recursos necesarios, estilos de css eimágenes.

**Comment by 0x01101** [comment]
En escritorio: 
![image](https://user-images.githubusercontent.com/23608115/93271124-e6527d00-f788-11ea-874d-769814681010.png)

**Comment by 0x01101** [comment]
En mobile: 
![image](https://user-images.githubusercontent.com/23608115/93381043-7995bc00-f836-11ea-896b-a3aacdc47226.png)
![image](https://user-images.githubusercontent.com/23608115/93381071-80243380-f836-11ea-801e-07a830aea570.png)
![image](https://user-images.githubusercontent.com/23608115/93381108-89150500-f836-11ea-8478-cc74798a44aa.png)
